apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-test
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sh", "-c", "env && sleep 3600"]
      envFrom:
        - configMapRef:
            name: test-config